name: Development branch
on:
  push: 
    branches:[ dev ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .Net 6
      with:
        dotnet-version '6.0.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .Net 6
      with:
        dotnet-version '6.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuratin Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
